### ISSUE TITLE
support for Erlang binaries

### ISSUE THREAD

**Issue by gdamjan** [erlangpack/erlang-oauth#22]
Currently you can't use binaries with oauth:signature, for Params for example.
And also can't use non-ascii in Params

**Comment by drozzy** [comment]
This still doesn't work for utf8 characters for me... :-(

E.g. this fails:

	Params = [
		{"four",  "☃"}
	]
	oauth:params_encode(Params),

**Comment by gdamjan** [comment]
@drozzy use binaries
```
Tag = <<226,152,131>>,
io:format("~ts~n", [Tag]),
Params = [{"four", Tag}],
oauth:params_encode(Params).
```

ps. I had to write Tag as such since the shell didn't allow me to paste the utf-8 string (YMMV).

**Comment by gdamjan** [comment]
ah, right
`Tag = <<"☃"/utf8>>.`

**Comment by drozzy** [comment]
@gdamjan I was writing that in an .erl file, which, as far as I know, allows for unicode characters.

So, are you saying that in each param `{k, v}` pair, the `v` must be a binary?

Thanks.

It would really be useful to have the function the escapes the string exported as well. I.e . something like:

`oauth:percent_encode("Ladies + Gentlemen") -> "Ladies%20%2B%20Gentlemen"`

`oauth:percent_encode("☃") -> "%E2%98%83"`

**Comment by tim** [comment]
@drozzy In each `{K, V}` pair `V` can be either a binary or a character list, but if you want to use unicode characters the values must be utf-8 encoded. For example:

```
1> oauth:params_encode([{"four", <<"☃"/utf8>>}]).
"four=%E2%98%83"
2> oauth:params_encode([{"four", [16#E2, 16#98, 16#83]}]).
"four=%E2%98%83"
```

If your data isn't utf-8 encoded then you need to convert it first.
