### ISSUE TITLE
Hex package

### ISSUE THREAD

**Issue by mworrell** [erlangpack/erlang-oauth#39]
Thanks for Erlang OAuth!
We use it in Zotonic for (among other things) the connection with Twitter.

Currently we are working on pushing all Zotonic modules and core to Hex.
That also involves having all dependencies on Hex as well.

Would you like to publish erlang-oauth to Hex?

**Comment by mworrell** [comment]
I have moved  the repo to erlangpack, will be adding the code for creating a package in the coming days.

**Comment by tim** [comment]
Great, thank you!

**Comment by mworrell** [comment]
We are now on hex:  https://hex.pm/packages/oauth

Thanks @tim !
